baseURL = 'https://VanillaViking.github.io'
languageCode = 'en-us'
title = 'Ashwin Rajesh'
theme = "ananke"
Paginate = 100
googleAnalytics = 'G-PM26JXPQWZ'

[Params]

background_color_class = "bg-navy"
body_classes = "avenir bg-near-white"
post_content_classes = "ubuntu"

ananke_socials = [
  { name = "github", url = "https://github.com/VanillaViking" },
  { name = "instagram", url = "https://www.instagram.com/ashwinr2k2" },
  { name = "linkedin", url = "https://www.linkedin.com/in/ashwin-rajesh-6a4960208/" }
]
